# Copyright 2014 OpenStack Foundation
#
#    Licensed under the Apache License, Version 2.0 (the "License"); you may
#    not use this file except in compliance with the License. You may obtain
#    a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#    License for the specific language governing permissions and limitations
#    under the License.
#

"""nexus_l3_plugin

Revision ID: 22c2b94a0f22
Revises: 2d2a8a565438
Create Date: 2014-10-20 10:51:10.718207

"""

# revision identifiers, used by Alembic.
revision = '22c2b94a0f22'
down_revision = '2d2a8a565438'

from alembic import op
import sqlalchemy as sa



def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cisco_nexus_vrf',
    sa.Column('vrf_id', sa.String(length=36), autoincrement=False, nullable=False),
    sa.Column('router_id', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('vrf_id'),
    mysql_engine='InnoDB'
    )
    op.create_table('cisco_nexus_vrf_binding',
    sa.Column('vrf_id', sa.String(length=36), nullable=False),
    sa.Column('switch_ip', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['vrf_id'], ['cisco_nexus_vrf.vrf_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('vrf_id', 'switch_ip'),
    mysql_engine='InnoDB'
    )


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cisco_nexus_vrf_binding')
    op.drop_table('cisco_nexus_vrf')
    ### end Alembic commands ###
