# Copyright 2014 OpenStack Foundation
#
#    Licensed under the Apache License, Version 2.0 (the "License"); you may
#    not use this file except in compliance with the License. You may obtain
#    a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#    License for the specific language governing permissions and limitations
#    under the License.
#

"""cisco_ml2_nexus_vxlan

Revision ID: 3bc23c072a91
Revises: 208b451f0e97
Create Date: 2014-09-11 19:50:55.964739

"""

# revision identifiers, used by Alembic.
revision = '3bc23c072a91'
down_revision = '208b451f0e97'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


def upgrade(active_plugins=None, options=None):
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cisco_ml2_nexus_nve',
    sa.Column('vni', sa.Integer(), nullable=False),
    sa.Column('switch_ip', sa.String(length=255), nullable=True),
    sa.Column('mcast_group', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('vni'),
    mysql_engine='InnoDB'
    )
#    op.drop_table('ml2_nexus_vxlan_allocations')
#    op.drop_table('ml2_nexus_vxlan_mcast_groups')
    op.add_column('cisco_ml2_nexusport_bindings', sa.Column('vni', sa.Integer(), nullable=True))
#    op.drop_index('embrane_pool_port_ibfk_2', table_name='embrane_pool_port')
    ### end Alembic commands ###


def downgrade(active_plugins=None, options=None):
    ### commands auto generated by Alembic - please adjust! ###
#    op.create_index('embrane_pool_port_ibfk_2', 'embrane_pool_port', ['port_id'], unique=False)
    op.drop_column('cisco_ml2_nexusport_bindings', 'vni')
#    op.create_table('ml2_nexus_vxlan_mcast_groups',
#    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
#    sa.Column('mcast_group', mysql.VARCHAR(length=64), nullable=False),
#    sa.Column('associated_vni', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
#    sa.ForeignKeyConstraint(['associated_vni'], [u'ml2_nexus_vxlan_allocations.vxlan_vni'], name=u'ml2_nexus_vxlan_mcast_groups_ibfk_1', ondelete=u'CASCADE'),
#    sa.PrimaryKeyConstraint('id'),
#    mysql_default_charset=u'utf8',
#    mysql_engine=u'InnoDB'
#    )
#    op.create_table('ml2_nexus_vxlan_allocations',
#    sa.Column('vxlan_vni', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
#    sa.Column('allocated', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
#    sa.PrimaryKeyConstraint('vxlan_vni'),
#    mysql_default_charset=u'utf8',
#    mysql_engine=u'InnoDB'
#    )
    op.drop_table('cisco_ml2_nexus_nve')
    ### end Alembic commands ###
