systemctl stop openstack-ceilometer-alarm-evaluator.service
systemctl stop openstack-ceilometer-alarm-notifier.service
systemctl stop openstack-ceilometer-api.service
systemctl stop openstack-ceilometer-central.service
systemctl stop openstack-ceilometer-collector.service
systemctl stop openstack-ceilometer-notification.service
systemctl stop openstack-cinder-api.service
systemctl stop openstack-cinder-backup.service
systemctl stop openstack-cinder-scheduler.service
systemctl stop openstack-cinder-volume.service
systemctl stop openstack-glance-api.service
systemctl stop openstack-glance-registry.service
systemctl stop openstack-heat-api.service
systemctl stop openstack-heat-engine.service
systemctl stop openstack-keystone.service
systemctl stop openstack-nova-api.service
systemctl stop openstack-nova-cert.service
systemctl stop openstack-nova-conductor.service
systemctl stop openstack-nova-consoleauth.service
systemctl stop openstack-nova-novncproxy.service
systemctl stop openstack-nova-scheduler.service
systemctl stop openstack-swift-account-auditor.service
systemctl stop openstack-swift-account-reaper.service
systemctl stop openstack-swift-account-replicator.service
systemctl stop openstack-swift-account.service
systemctl stop openstack-swift-container-auditor.service
systemctl stop openstack-swift-container-replicator.service
systemctl stop openstack-swift-container-updater.service
systemctl stop openstack-swift-container.service
systemctl stop openstack-swift-object-auditor.service
systemctl stop openstack-swift-object-replicator.service
systemctl stop openstack-swift-object-updater.service
systemctl stop openstack-swift-object.service
systemctl stop openstack-swift-proxy.service
systemctl stop neutron-cisco-cfg-agent.service
systemctl stop neutron-dhcp-agent.service
systemctl stop neutron-metadata-agent.service
systemctl stop neutron-openvswitch-agent.service
systemctl stop neutron-server.service
